export const usdc = [
  {
    name: "USDC (Ethereum)",
    symbol: "usdc",
    network: "eth",
    has_extra_id: false,
    extra_id: "",
    image: "https://static.simpleswap.io/images/currencies-logo/usdc.svg",
    warnings_from: [
      "Please note that USDC is expected to be deposited on the ETH network.",
    ],
    warnings_to: ["Please note USDC will be sent on the ETH network."],
    validation_address: "^(0x)[0-9A-Fa-f]{40}$",
    validation_extra: null,
    address_explorer: "https://etherscan.io/address/{}",
    tx_explorer: "https://etherscan.io/tx/{}",
    confirmations_from: "",
    contract_address: "0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48",
    isFiat: false,
    trace_id: "e47fc3fa-1fe8-4b82-85cf-effc01fad81f",
  },
  {
    name: "USDC (Matic)",
    symbol: "usdcpoly",
    network: "matic",
    has_extra_id: false,
    extra_id: "",
    image: "https://static.simpleswap.io/images/currencies-logo/usdcpoly.svg",
    warnings_from: [],
    warnings_to: ["Please note USDC will be sent on the MATIC network."],
    validation_address: "^(0x)[0-9A-Fa-f]{40}$",
    validation_extra: null,
    address_explorer: "https://polygonscan.com/address/{}",
    tx_explorer: "https://polygonscan.com/tx/{}",
    confirmations_from: "",
    contract_address: "0x3c499c542cEF5E3811e1192ce70d8cC03d5c3359",
    isFiat: false,
    trace_id: "8826c335-1f8e-4608-9530-8496f5d5815d",
  },
  {
    name: "USDC (Solana)",
    symbol: "usdcspl",
    network: "solana",
    has_extra_id: false,
    extra_id: "",
    image: "https://static.simpleswap.io/images/currencies-logo/usdcspl.svg",
    warnings_from: [],
    warnings_to: ["Please note USDC will be sent on the SOLANA network."],
    validation_address: "^[1-9A-HJ-NP-Za-km-z]{32,44}$",
    validation_extra: null,
    address_explorer: "https://solscan.io/account/{}",
    tx_explorer: "https://solscan.io/tx/{}",
    confirmations_from: "",
    contract_address: "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
    isFiat: false,
    trace_id: "d2289804-4cb1-4313-91cf-50151fb6f66c",
  },
  {
    name: "USDC (BSC)",
    symbol: "usdcbep20",
    network: "bsc",
    has_extra_id: false,
    extra_id: "",
    image: "https://static.simpleswap.io/images/currencies-logo/usdcbep20.svg",
    warnings_from: [
      "Please note that USDC is expected to be deposited on the BSC network.",
    ],
    warnings_to: ["Please note USDC will be sent on the BSC network."],
    validation_address: "^(0x)[0-9A-Fa-f]{40}$",
    validation_extra: null,
    address_explorer: "https://bscscan.com/address/{}",
    tx_explorer: "https://bscscan.com/tx/{}",
    confirmations_from: "",
    contract_address: "0x8ac76a51cc950d9822d68b83fe1ad97b32cd580d",
    isFiat: false,
    trace_id: "e408dd12-ef88-4af6-93b8-9a06f0b0778d",
  },
  {
    name: "USDC (Algo)",
    symbol: "usdcalgo",
    network: "algo",
    has_extra_id: true,
    extra_id: "note",
    image: "https://static.simpleswap.io/images/currencies-logo/usdcalgo.svg",
    warnings_from: [],
    warnings_to: ["Please note USDC will be sent on the ALGO network."],
    validation_address: "^[A-Z0-9]{58,58}$",
    validation_extra: null,
    address_explorer: "https://allo.info/account/{}/txns",
    tx_explorer: "https://allo.info/tx/{}",
    confirmations_from: "",
    contract_address: "31566704",
    isFiat: false,
    trace_id: "bed44e73-a804-46ba-be0b-d190a2e28be1",
  },
  {
    name: "USDC (Avax-c)",
    symbol: "usdcavaxc",
    network: "avax-c",
    has_extra_id: false,
    extra_id: "",
    image: "https://static.simpleswap.io/images/currencies-logo/usdcavaxc.svg",
    warnings_from: [],
    warnings_to: ["Please note USDC will be sent on the AVAX-C network."],
    validation_address: "^(0x)[0-9A-Fa-f]{40}$",
    validation_extra: null,
    address_explorer: "https://snowtrace.io/address/{}",
    tx_explorer: "https://snowtrace.io/tx/{}",
    confirmations_from: "",
    contract_address: "0xB97EF9Ef8734C71904D8002F8b6Bc66Dd9c48a6E",
    isFiat: false,
    trace_id: "a5321b81-1982-43ee-ba58-f46d5085b73d",
  },
  {
    name: "USDC Bridged (USDC.e)",
    symbol: "usdceop",
    network: "optimism",
    has_extra_id: false,
    extra_id: "",
    image: "https://static.simpleswap.io/images/currencies-logo/usdceop.svg",
    warnings_from: [
      "Please note: USDC.E OPTIMISM (bridged version) is expected to be deposited.",
    ],
    warnings_to: ["Please note OPUSDCE will be sent on the OPTIMISM network."],
    validation_address: "^(0x)[0-9A-Fa-f]{40}$",
    validation_extra: null,
    address_explorer: "https://optimistic.etherscan.io/address/{}",
    tx_explorer: "https://optimistic.etherscan.io/tx/{}",
    confirmations_from: "",
    contract_address: "0x7F5c764cBc14f9669B88837ca1490cCa17c31607",
    isFiat: false,
    trace_id: "17b402a0-dc28-4985-8668-08121704011d",
  },
  {
    name: "USDC (Arbitrum)",
    symbol: "usdcarb",
    network: "arbitrum",
    has_extra_id: false,
    extra_id: "",
    image: "https://static.simpleswap.io/images/currencies-logo/usdcarb.svg",
    warnings_from: [
      "Please note that USDC is expected to be deposited on the ARBITRUM network.",
    ],
    warnings_to: ["Please note USDC will be sent on the ARBITRUM network."],
    validation_address: "^(0x)[0-9A-Fa-f]{40}$",
    validation_extra: null,
    address_explorer: "https://arbiscan.io/address/{}",
    tx_explorer: "https://arbiscan.io/tx/{}",
    confirmations_from: "",
    contract_address: "0xaf88d065e77c8cc2239327c5edb3a432268e5831",
    isFiat: false,
    trace_id: "ce7f8f03-3d67-4e81-8c0e-f3d01d93d1d3",
  },
  {
    name: "USDC (Stellar)",
    symbol: "usdcxlm",
    network: "xlm",
    has_extra_id: true,
    extra_id: "memo",
    image: "https://static.simpleswap.io/images/currencies-logo/usdcxlm.svg",
    warnings_from: [],
    warnings_to: ["Please note USDC will be sent on the XLM network."],
    validation_address: "^G[A-D]{1}[A-Z2-7]{54}$",
    validation_extra: "^[0-9A-Za-z-]{1,28}$",
    address_explorer: "https://stellar.expert/explorer/public/account/{}",
    tx_explorer: "https://stellar.expert/explorer/public/tx/{}",
    confirmations_from: "",
    contract_address:
      "USDC-GA5ZSEJYB37JRC5AVCIA5MOP4RHTM335X2KGX3IHOJAPP5RE34K4KZVN",
    isFiat: false,
    trace_id: "6bcbd0c4-5ddb-49b0-980c-07770b9cb9b4",
  },
  {
    name: "USDC (Ronin)",
    symbol: "usdcron",
    network: "ron",
    has_extra_id: false,
    extra_id: "",
    image: "https://static.simpleswap.io/images/currencies-logo/usdcron.svg",
    warnings_from: [],
    warnings_to: ["Please note USDC will be sent on the RON network."],
    validation_address: "^(0x)[0-9A-Fa-f]{40}$",
    validation_extra: null,
    address_explorer: "https://explorer.roninchain.com/address/{}",
    tx_explorer: "https://explorer.roninchain.com/tx/{}",
    confirmations_from: "",
    contract_address: "0x0b7007c13325c48911f73a2dad5fa5dcbf808adc",
    isFiat: false,
    trace_id: "01fcd988-25de-471d-9441-d1e9a64bdced",
  },
  {
    name: "USDC (KCC)",
    symbol: "usdckcc",
    network: "kcc",
    has_extra_id: false,
    extra_id: "",
    image: "https://static.simpleswap.io/images/currencies-logo/usdckcc.svg",
    warnings_from: [],
    warnings_to: ["Please note USDC will be sent on the KCC network."],
    validation_address: "^(0x)[0-9A-Fa-f]{40}$",
    validation_extra: null,
    address_explorer: "https://explorer.kcc.io/en/address/{}",
    tx_explorer: "https://explorer.kcc.io/en/tx/{}",
    confirmations_from: "",
    contract_address: "0x980a5afef3d17ad98635f6c5aebcbaeded3c3430",
    isFiat: false,
    trace_id: "9cc04625-5f05-45c8-bd94-959d2001af8f",
  },
  {
    name: "USDC",
    symbol: "usdcbase",
    network: "base",
    has_extra_id: false,
    extra_id: "",
    image: "https://static.simpleswap.io/images/currencies-logo/usdcbase.svg",
    warnings_from: [],
    warnings_to: ["Please note USDC will be sent on the BASE network."],
    validation_address: "^(0x)[0-9A-Fa-f]{40}$",
    validation_extra: null,
    address_explorer: "https://basescan.org/address/{}",
    tx_explorer: "https://basescan.org/tx/{}",
    confirmations_from: "",
    contract_address: "0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913",
    isFiat: false,
    trace_id: "be820f72-fa13-4507-a769-0c1f58ebae13",
  },
  {
    name: "USDC (Celo)",
    symbol: "usdccelo",
    network: "celo",
    has_extra_id: false,
    extra_id: "",
    image: "https://static.simpleswap.io/images/currencies-logo/usdccelo.svg",
    warnings_from: [],
    warnings_to: ["Please note USDC will be sent on the CELO network."],
    validation_address: "^(0x)[0-9A-Fa-f]{40}$",
    validation_extra: null,
    address_explorer: "https://celoscan.io/address/{}",
    tx_explorer: "https://celoscan.io/tx/{}",
    confirmations_from: "",
    contract_address: "0xceba9300f2b948710d2653dd7b07f33a8b32118c",
    isFiat: false,
    trace_id: "201771d9-2f33-47d4-9afa-54c5aef41f5f",
  },
  {
    name: "USDC Bridged (USDC.e)",
    symbol: "usdcearb",
    network: "arbitrum",
    has_extra_id: false,
    extra_id: "",
    image: "https://static.simpleswap.io/images/currencies-logo/usdcearb.svg",
    warnings_from: [
      "Please note: USDC.E ARBITRUM (bridged version) is expected to be deposited.",
    ],
    warnings_to: ["Please note ARBUSDCE will be sent on the ARBITRUM network."],
    validation_address: "^(0x)[0-9A-Fa-f]{40}$",
    validation_extra: null,
    address_explorer: "https://arbiscan.io/address/{}",
    tx_explorer: "https://arbiscan.io/tx/{}",
    confirmations_from: "",
    contract_address: "0xFF970A61A04b1cA14834A43f5dE4533eBDDB5CC8",
    isFiat: false,
    trace_id: "95cfe8ff-ee1b-4cec-835b-aa586e7ec0ae",
  },
  {
    name: "USDC Bridged (USDC.e)",
    symbol: "usdcepoly",
    network: "matic",
    has_extra_id: false,
    extra_id: "",
    image: "https://static.simpleswap.io/images/currencies-logo/usdcepoly.svg",
    warnings_from: [
      "Please note: USDC.E MATIC (bridged version) is expected to be deposited.",
    ],
    warnings_to: ["Please note MATICUSDCE will be sent on the MATIC network."],
    validation_address: "^(0x)[0-9A-Fa-f]{40}$",
    validation_extra: null,
    address_explorer: "https://polygonscan.com/address/{}",
    tx_explorer: "https://polygonscan.com/tx/{}",
    confirmations_from: "",
    contract_address: "0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174",
    isFiat: false,
    trace_id: "aca04c07-a031-44f6-a647-1c87e2c527d4",
  },
  {
    name: "USDC (Optimism)",
    symbol: "usdcop",
    network: "optimism",
    has_extra_id: false,
    extra_id: "",
    image: "https://static.simpleswap.io/images/currencies-logo/usdcop.svg",
    warnings_from: [],
    warnings_to: ["Please note USDC will be sent on the OPTIMISM network."],
    validation_address: "^(0x)[0-9A-Fa-f]{40}$",
    validation_extra: null,
    address_explorer: "https://optimistic.etherscan.io/address/{}",
    tx_explorer: "https://optimistic.etherscan.io/tx/{}",
    confirmations_from: "",
    contract_address: "0x0b2C639c533813f4Aa9D7837CAf62653d097Ff85",
    isFiat: false,
    trace_id: "8b85d5c1-dc0e-42ca-a4a0-83329e051c71",
  },
  {
    name: "USDC (Polcadot)",
    symbol: "usdcdot",
    network: "dot",
    has_extra_id: false,
    extra_id: "",
    image: "https://static.simpleswap.io/images/currencies-logo/usdcdot.svg",
    warnings_from: [],
    warnings_to: ["Please note USDC will be sent on the DOT network."],
    validation_address: "^(1)[0-9a-z-A-Z]{44,50}$",
    validation_extra: null,
    address_explorer: "https://assethub-polkadot.subscan.io/account/{}",
    tx_explorer: "https://assethub-polkadot.subscan.io/extrinsic/{}",
    confirmations_from: "",
    contract_address: null,
    isFiat: false,
    trace_id: "7340c22d-6fbb-4319-aebf-701344bfc3c8",
  },
  {
    name: "USDC (Near)",
    symbol: "usdcnear",
    network: "near",
    has_extra_id: false,
    extra_id: "",
    image: "https://static.simpleswap.io/images/currencies-logo/usdcnear.svg",
    warnings_from: [],
    warnings_to: ["Please note USDC will be sent on the NEAR network."],
    validation_address:
      "^(?!0x)(?!bc1)(?!bnb1)[a-z0-9_-]{1}[a-z0-9_.-]{0,62}[a-z0-9_-]{1}$",
    validation_extra: null,
    address_explorer: "https://getblock.io/explorers/near/accounts/{}",
    tx_explorer: "https://getblock.io/explorers/near/transactions/{}",
    confirmations_from: "",
    contract_address:
      "17208628f84f5d6ad33f0da3bbbeb27ffcb398eac501a31bd6ad2011e36133a1",
    isFiat: false,
    trace_id: "84cc4257-1289-41b3-bc1c-70fa6a04a9e0",
  },
  {
    name: "USDC",
    symbol: "usdczk",
    network: "zkSync",
    has_extra_id: false,
    extra_id: "",
    image: "https://static.simpleswap.io/images/currencies-logo/usdczk.svg",
    warnings_from: [],
    warnings_to: [],
    validation_address: "^(0x)[0-9A-Fa-f]{40}$",
    validation_extra: null,
    address_explorer: "https://explorer.zksync.io/address/{}",
    tx_explorer: "https://explorer.zksync.io/tx/{}",
    confirmations_from: "",
    contract_address: "0x1d17cbcf0d6d143135ae902365d2e5e2a16538d4",
    isFiat: false,
    trace_id: "d7aabbb3-2998-4143-bf44-fef39abec37e",
  },
];
