export const usdt = [
  {
    name: "Tether USD (Ethereum)",
    symbol: "usdterc20",
    network: "eth",
    has_extra_id: false,
    extra_id: "",
    image: "https://static.simpleswap.io/images/currencies-logo/usdterc20.svg",
    warnings_from: [
      "Please note that USDT is expected to be deposited on the ETH network.",
    ],
    warnings_to: ["Please note USDT will be sent on the ETH network."],
    validation_address: "^(0x)[0-9A-Fa-f]{40}$",
    validation_extra: null,
    address_explorer: "https://etherscan.io/address/{}",
    tx_explorer: "https://etherscan.io/tx/{}",
    confirmations_from: "",
    contract_address: "0xdac17f958d2ee523a2206206994597c13d831ec7",
    isFiat: false,
    trace_id: "1d31e535-3d27-47db-b8d0-449865f83bf1",
  },
  {
    name: "Tether USD (Tron)",
    symbol: "usdttrc20",
    network: "trx",
    has_extra_id: false,
    extra_id: "",
    image: "https://static.simpleswap.io/images/currencies-logo/usdttrc20.svg",
    warnings_from: [],
    warnings_to: ["Please note USDT will be sent on the TRX network."],
    validation_address: "^T[1-9A-HJ-NP-Za-km-z]{33}$",
    validation_extra: null,
    address_explorer: "https://tronscan.org/#/address/{}",
    tx_explorer: "https://tronscan.org/#/transaction/{}",
    confirmations_from: "",
    contract_address: "TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t",
    isFiat: false,
    trace_id: "4b4004cb-a517-46ae-8330-62741b381947",
  },
  {
    name: "Tether USD (BSC)",
    symbol: "usdtbep20",
    network: "bsc",
    has_extra_id: false,
    extra_id: "",
    image: "https://static.simpleswap.io/images/currencies-logo/usdtbep20.svg",
    warnings_from: [
      "Please note that USDT is expected to be deposited on the BSC network.",
    ],
    warnings_to: ["Please note USDT will be sent on the BSC network."],
    validation_address: "^(0x)[0-9A-Fa-f]{40}$",
    validation_extra: null,
    address_explorer: "https://bscscan.com/address/{}",
    tx_explorer: "https://bscscan.com/tx/{}",
    confirmations_from: "",
    contract_address: "0x55d398326f99059ff775485246999027b3197955",
    isFiat: false,
    trace_id: "eaa199d3-a600-4d4e-89b4-3896025df95f",
  },
  {
    name: "Tether USD (Solana)",
    symbol: "usdtspl",
    network: "solana",
    has_extra_id: false,
    extra_id: "",
    image: "https://static.simpleswap.io/images/currencies-logo/usdtspl.svg",
    warnings_from: [],
    warnings_to: ["Please note USDT will be sent on the SOLANA network."],
    validation_address: "^[1-9A-HJ-NP-Za-km-z]{32,44}$",
    validation_extra: null,
    address_explorer: "https://solscan.io/account/{}",
    tx_explorer: "https://solscan.io/tx/{}",
    confirmations_from: "",
    contract_address: "Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB",
    isFiat: false,
    trace_id: "4ea21a9e-85d3-4a10-a567-a06a3d1a34f9",
  },
  {
    name: "Tether USD (Polygon)",
    symbol: "usdtpoly",
    network: "matic",
    has_extra_id: false,
    extra_id: "",
    image: "https://static.simpleswap.io/images/currencies-logo/usdtpoly.svg",
    warnings_from: [],
    warnings_to: ["Please note USDT will be sent on the MATIC network."],
    validation_address: "^(0x)[0-9A-Fa-f]{40}$",
    validation_extra: null,
    address_explorer: "https://polygonscan.com/address/{}",
    tx_explorer: "https://polygonscan.com/tx/{}",
    confirmations_from: "",
    contract_address: "0xc2132D05D31c914a87C6611C10748AEb04B58e8F",
    isFiat: false,
    trace_id: "50afb04a-3745-4ed1-b4bb-0cae7fd1f78d",
  },
  {
    name: "Tether USD (Avax-C)",
    symbol: "usdtavaxc",
    network: "avax-c",
    has_extra_id: false,
    extra_id: "",
    image: "https://static.simpleswap.io/images/currencies-logo/usdtavaxc.svg",
    warnings_from: [],
    warnings_to: ["Please note USDT will be sent on the AVAX-C network."],
    validation_address: "^(0x)[0-9A-Fa-f]{40}$",
    validation_extra: null,
    address_explorer: "https://snowtrace.io/address/{}",
    tx_explorer: "https://snowtrace.io/tx/{}",
    confirmations_from: "",
    contract_address: "0x9702230A8Ea53601f5cD2dc00fDBc13d4dF4A8c7",
    isFiat: false,
    trace_id: "a8d5cf53-312f-4038-9ea4-aad38f3213f8",
  },
  {
    name: "Tether USD (Arbitrum)",
    symbol: "usdtarb",
    network: "arbitrum",
    has_extra_id: false,
    extra_id: "",
    image: "https://static.simpleswap.io/images/currencies-logo/usdtarb.svg",
    warnings_from: [],
    warnings_to: ["Please note USDT will be sent on the ARBITRUM network."],
    validation_address: "^(0x)[0-9A-Fa-f]{40}$",
    validation_extra: null,
    address_explorer: "https://arbiscan.io/address/{}",
    tx_explorer: "https://arbiscan.io/tx/{}",
    confirmations_from: "",
    contract_address: "0xFd086bC7CD5C481DCC9C85ebE478A1C0b69FCbb9",
    isFiat: false,
    trace_id: "b7131923-655d-4530-b4e2-b014a1598ea4",
  },
  {
    name: "Tether USD (Optimism)",
    symbol: "usdtop",
    network: "optimism",
    has_extra_id: false,
    extra_id: "",
    image: "https://static.simpleswap.io/images/currencies-logo/usdtop.svg",
    warnings_from: [],
    warnings_to: ["Please note USDT will be sent on the OPTIMISM network."],
    validation_address: "^(0x)[0-9A-Fa-f]{40}$",
    validation_extra: null,
    address_explorer: "https://optimistic.etherscan.io/address/{}",
    tx_explorer: "https://optimistic.etherscan.io/tx/{}",
    confirmations_from: "",
    contract_address: "0x94b008aA00579c1307B0EF2c499aD98a8ce58e58",
    isFiat: false,
    trace_id: "e0c3a9b7-0f22-4f6b-aa6a-d2dbf7ef89cf",
  },
  {
    name: "Tether USD (Near)",
    symbol: "usdtnear",
    network: "near",
    has_extra_id: false,
    extra_id: "",
    image: "https://static.simpleswap.io/images/currencies-logo/usdtnear.svg",
    warnings_from: [],
    warnings_to: ["Please note USDT will be sent on the NEAR network."],
    validation_address:
      "^(?!0x)(?!bc1)(?!bnb1)[a-z0-9_-]{1}[a-z0-9_.-]{0,62}[a-z0-9_-]{1}$",
    validation_extra: null,
    address_explorer: "https://getblock.io/explorers/near/accounts/{}",
    tx_explorer: "https://getblock.io/explorers/near/transactions/{}",
    confirmations_from: "",
    contract_address: "usdt.tether-token.near",
    isFiat: false,
    trace_id: "a011a71b-b140-4038-9ee2-ec8f3b22f723",
  },
  {
    name: "Tether USD (KAVA)",
    symbol: "usdtkavaevm",
    network: "kavaevm",
    has_extra_id: false,
    extra_id: "",
    image:
      "https://static.simpleswap.io/images/currencies-logo/usdtkavaevm.svg",
    warnings_from: [],
    warnings_to: ["Please note USDT will be sent on the KAVAEVM network."],
    validation_address: "^(0x)[0-9A-Fa-f]{40}$",
    validation_extra: null,
    address_explorer: "https://explorer.kava.io/address/{}",
    tx_explorer: "https://explorer.kava.io/tx/{}",
    confirmations_from: "",
    contract_address: "0x919c1c267bc06a7039e03fcc2ef738525769109c",
    isFiat: false,
    trace_id: "f17f031e-ef35-4b73-8ebd-be5bdcb78cde",
  },
  {
    name: "Tether USD (Eos)",
    symbol: "usdteos",
    network: "eos",
    has_extra_id: true,
    extra_id: "memo",
    image: "https://static.simpleswap.io/images/currencies-logo/usdteos.svg",
    warnings_from: [],
    warnings_to: ["Please note USDT will be sent on the EOS network."],
    validation_address: "^[1-5a-z\\.]{1,12}$",
    validation_extra: "^[0-9A-Za-z\\-_,]{1,120}$",
    address_explorer: "https://eosauthority.com/account/{}?network=eos",
    tx_explorer: "https://eosauthority.com/transaction/{}?network=eos",
    confirmations_from: "",
    contract_address: "tethertether",
    isFiat: false,
    trace_id: "ab2af871-05f0-4b9f-b39c-f1c82a6111fa",
  },
  {
    name: "Tether USD (Tezos)",
    symbol: "usdtxtz",
    network: "xtz",
    has_extra_id: false,
    extra_id: "",
    image: "https://static.simpleswap.io/images/currencies-logo/usdtxtz.svg",
    warnings_from: [],
    warnings_to: ["Please note USDT will be sent on the XTZ network."],
    validation_address: "^(tz[1,2,3])[a-zA-Z0-9]{33}$",
    validation_extra: null,
    address_explorer: "https://tzkt.io/{}",
    tx_explorer: "https://tzkt.io/{}",
    confirmations_from: "",
    contract_address: "KT1XnTn74bUtxHfDtBmm2bGZAQfhPbvKWR8o",
    isFiat: false,
    trace_id: "622dd4f7-d135-49b7-a050-8f6866e03407",
  },
  {
    name: "Tether USD (TON)",
    symbol: "usdtton",
    network: "ton",
    has_extra_id: true,
    extra_id: "memo",
    image: "https://static.simpleswap.io/images/currencies-logo/usdtton.svg",
    warnings_from: [],
    warnings_to: ["Please note USDT will be sent on the TON network."],
    validation_address: "^[UE][Qf][0-9a-z-A-Z\\-\\_]{46}$",
    validation_extra: "^[0-9A-Za-z\\-_]{1,120}$",
    address_explorer: "https://tonscan.org/address/{}",
    tx_explorer: "https://tonscan.org/tx/{}",
    confirmations_from: "",
    contract_address: "EQCxE6mUtQJKFnGfaROTKOt1lZbDiiX1kCixRv7Nw2Id_sDs",
    isFiat: false,
    trace_id: "11bfaeae-f33d-478d-b84f-ada322cac1f0",
  },
  {
    name: "Tether USD (Celo)",
    symbol: "usdtcelo",
    network: "celo",
    has_extra_id: false,
    extra_id: "",
    image: "https://static.simpleswap.io/images/currencies-logo/usdtcelo.svg",
    warnings_from: [],
    warnings_to: ["Please note USDT will be sent on the CELO network."],
    validation_address: "^(0x)[0-9A-Fa-f]{40}$",
    validation_extra: null,
    address_explorer: "https://celoscan.io/address/{}",
    tx_explorer: "https://celoscan.io/tx/{}",
    confirmations_from: "",
    contract_address: "0x48065fbbe25f71c9282ddf5e1cd6d6a887483d5e",
    isFiat: false,
    trace_id: "a67d4eb0-6fa4-45f8-a366-a9d5a65e1f68",
  },
  {
    name: "Tether USD (Polkadot)",
    symbol: "usdtdot",
    network: "dot",
    has_extra_id: false,
    extra_id: "",
    image: "https://static.simpleswap.io/images/currencies-logo/usdtdot.svg",
    warnings_from: [],
    warnings_to: ["Please note USDT will be sent on the DOT network."],
    validation_address: "^(1)[0-9a-z-A-Z]{44,50}$",
    validation_extra: null,
    address_explorer: "https://assethub-polkadot.subscan.io/account/{}",
    tx_explorer: "https://assethub-polkadot.subscan.io/extrinsic/{}",
    confirmations_from: "",
    contract_address: null,
    isFiat: false,
    trace_id: "5f2f5de3-136f-4898-b0ca-078cce16e55b",
  },
];
