export const crypto = [
  {
    name: "Bitcoin",
    symbol: "btc",
    network: "btc",
    has_extra_id: false,
    extra_id: "",
    image: "https://static.simpleswap.io/images/currencies-logo/btc.svg",
    warnings_from: [],
    warnings_to: [],
    validation_address:
      "^[13][a-km-zA-HJ-NP-Z1-9]{25,34}$|^[(bc1q)|(bc1p)][0-9A-Za-z]{37,62}$",
    validation_extra: null,
    address_explorer: "https://mempool.space/address/{}",
    tx_explorer: "https://mempool.space/tx/{}",
    confirmations_from: "",
    contract_address: null,
    isFiat: false,
    trace_id: "0526a895-352c-45aa-9dee-82b04ec75d0b",
  },
  {
    name: "Solana",
    symbol: "sol",
    network: "sol",
    has_extra_id: false,
    extra_id: "",
    image: "https://static.simpleswap.io/images/currencies-logo/sol.svg",
    warnings_from: [],
    warnings_to: [],
    validation_address: "^[1-9A-HJ-NP-Za-km-z]{32,44}$",
    validation_extra: null,
    address_explorer: "https://explorer.solana.com/account/{}",
    tx_explorer: "https://explorer.solana.com/tx/{}",
    confirmations_from: "",
    contract_address: null,
    isFiat: false,
    trace_id: "38190b8c-539e-457d-bd12-d48f99944314",
  },
  {
    name: "Ethereum",
    symbol: "eth",
    network: "eth",
    has_extra_id: false,
    extra_id: "",
    image: "https://static.simpleswap.io/images/currencies-logo/eth.svg",
    warnings_from: [
      "Please deposit ETH using the main Ethereum (ETH) network.",
    ],
    warnings_to: [],
    validation_address: "^(0x)[0-9A-Fa-f]{40}$",
    validation_extra: null,
    address_explorer: "https://etherscan.io/address/{}",
    tx_explorer: "https://etherscan.io/tx/{}",
    confirmations_from: "",
    contract_address: null,
    isFiat: false,
    trace_id: "caaa448c-2e0f-4c0d-971f-fd167280f577",
  },
  {
    name: "Monero",
    symbol: "xmr",
    network: "xmr",
    has_extra_id: false,
    extra_id: "",
    image: "https://static.simpleswap.io/images/currencies-logo/xmr.svg",
    warnings_from: [],
    warnings_to: [],
    validation_address: "^[48][a-zA-Z|\\d]{94}([a-zA-Z|\\d]{11})?$",
    validation_extra: null,
    address_explorer: null,
    tx_explorer: "https://xmrchain.net/search?value={}",
    confirmations_from: "",
    contract_address: null,
    isFiat: false,
    trace_id: "28b6fc63-d748-4906-bea4-8405c110a6a8",
  },
  {
    name: "Litecoin",
    symbol: "ltc",
    network: "ltc",
    has_extra_id: false,
    extra_id: "",
    image: "https://static.simpleswap.io/images/currencies-logo/ltc.svg",
    warnings_from: [],
    warnings_to: [],
    validation_address: "^(L|M)[A-Za-z0-9]{33}$|^(ltc1)[0-9A-Za-z]{39}$",
    validation_extra: null,
    address_explorer: "https://explorer.litecoin.net/address/{}",
    tx_explorer: "https://explorer.litecoin.net/tx/{}",
    confirmations_from: "",
    contract_address: null,
    isFiat: false,
    trace_id: "a81597a3-8d41-405c-91b5-92568325e8f8",
  },
  {
    name: "XRP",
    symbol: "xrp",
    network: "xrp",
    has_extra_id: true,
    extra_id: "Destination tag",
    image: "https://static.simpleswap.io/images/currencies-logo/xrp.svg",
    warnings_from: [],
    warnings_to: [],
    validation_address: "^r[1-9A-HJ-NP-Za-km-z]{25,34}$",
    validation_extra: "^((?!0)[0-9]{1,10})$",
    address_explorer: "https://xrpscan.com/account/{}",
    tx_explorer: "https://xrpscan.com/tx/{}",
    confirmations_from: "",
    contract_address: null,
    isFiat: false,
    trace_id: "c41b0d65-cb8d-4d35-bfd3-29154cea06e8",
  },
  {
    name: "NEAR Protocol",
    symbol: "near",
    network: "near",
    has_extra_id: false,
    extra_id: "",
    image: "https://static.simpleswap.io/images/currencies-logo/near.svg",
    warnings_from: [],
    warnings_to: [],
    validation_address:
      "^(?!0x)(?!bc1)(?!bnb1)[a-z0-9_-]{1}[a-z0-9_.-]{0,62}[a-z0-9_-]{1}$",
    validation_extra: null,
    address_explorer: "https://getblock.io/explorers/near/accounts/{}",
    tx_explorer: "https://getblock.io/explorers/near/transactions/{}",
    confirmations_from: "",
    contract_address: null,
    isFiat: false,
    trace_id: "a52cbd18-f200-4060-b42d-15906535d5b0",
  },
  {
    name: "Binance Coin (Mainnet)",
    symbol: "bnb",
    network: "bnb",
    has_extra_id: true,
    extra_id: "Memo",
    image: "https://static.simpleswap.io/images/currencies-logo/bnb.svg",
    warnings_from: [],
    warnings_to: [],
    validation_address: "^(bnb1)[0-9a-z]{38}$",
    validation_extra: "^[0-9A-Za-z\\-_]{1,120}$",
    address_explorer: "https://explorer.binance.org/address/{}",
    tx_explorer: "https://explorer.binance.org/tx/{}",
    confirmations_from: "",
    contract_address: null,
    isFiat: false,
    trace_id: "86101b3a-7bff-4041-8fc0-5f18a6e74e9f",
  },
  {
    name: "Cardano",
    symbol: "ada",
    network: "ada",
    has_extra_id: false,
    extra_id: "",
    image: "https://static.simpleswap.io/images/currencies-logo/ada.svg",
    warnings_from: [],
    warnings_to: [],
    validation_address: "^(([0-9A-Za-z]{57,59})|([0-9A-Za-z]{100,104}))$",
    validation_extra: null,
    address_explorer: "https://cardanoscan.io/address/{}",
    tx_explorer: "https://cardanoscan.io/transaction/{}",
    confirmations_from: "",
    contract_address: null,
    isFiat: false,
    trace_id: "a4842971-179a-49db-a606-1d137863ca55",
  },
  {
    name: "Avalanche",
    symbol: "avax",
    network: "AVAX-X",
    has_extra_id: false,
    extra_id: "",
    image: "https://static.simpleswap.io/images/currencies-logo/avax.svg",
    warnings_from: [],
    warnings_to: ["Please note AVAX will be sent on the AVAX-X network."],
    validation_address: "^(X-avax)[0-9A-za-z]{39}$",
    validation_extra: null,
    address_explorer: "https://avascan.info/blockchain/x/address/{}",
    tx_explorer: "https://avascan.info/blockchain/x/tx/{}",
    confirmations_from: "",
    contract_address: null,
    isFiat: false,
    trace_id: "d4c88b48-02a1-46af-9bd2-0d3a8fb127ba",
  },
];
