export const DEFI_APP_LIST: Record<string, APP_INFO> = {
  aftermath: {
    jumbotron_image: "/defi/aftermath-app.png",
    logo: "",
    url: "https://aftermath.finance/",
    title: "Aftermath",
    description: "",
    tagline: "",
    tags: ["DEX", "Liquid Staking"],
  },
  navi: {
    jumbotron_image: "",
    logo: "",
    url: "https://naviprotocol.io/",
    title: "Navi",
    description: `NAVI offers over collateralized lending/borrowing for SUI, USDC, USDT, wETH and wBTC and supports features like isolated pool, flash loan and soon to come crosschain lending/borrowing.`,
    tagline: "",
    tags: ["DEX"],
  },
  flowx: {
    jumbotron_image: "",
    logo: "",
    url: "https://flowx.finance/",
    title: "FlowX",
    description: `FlowX Finance is the ecosystem-focused decentralized exchange built on the Sui Blockchain`,
    tagline:
      "FlowX Finance is the ecosystem-focused decentralized exchange built on the Sui Blockchain",
    tags: ["DEX"],
  },
  bucket: {
    jumbotron_image: "/defi/bucket-app.png",
    logo: "",
    url: "https://www.bucketprotocol.io/",
    title: "Bucket",
    description: "some coin thingy",
    tagline: "Bucket Protocol",
    tags: ["CDP"],
  },
  molefi: {
    jumbotron_image: "",
    logo: "",
    url: "https://mole.fi/",
    title: "Molefi",
    description: `Mole is a DeFi protocol provided leveraged yield farming, hedge fund and savings.`,
    tagline:
      "Mole is a DeFi protocol provided leveraged yield farming, hedge fund and savings.",
    tags: ["Yield"],
  },
  typusfinance: {
    jumbotron_image: "/defi/typus-app.png",
    logo: "",
    url: "https://typus.finance/",
    title: "Typus Finance",
    description: `Real yield infrastructure on Sui`,
    tagline: "Real yield infrastructure on Sui",
    tags: ["Yield"],
  },
  cetus: {
    jumbotron_image: "/defi/cetus-app.webp",
    logo: "",
    url: "https://app.cetus.zone/",
    title: "Cetus",
    description:
      "Cetus is a pioneer DEX and concentrated liquidity protocol focusing on Move-based ecosystems like Aptos and Sui. It works as a crucial part of the ecosystem infrastructure to satisfy the comprehensive needs of traders, LPs, upper applications and an increasing DeFi population.",
    tagline: "",
    tags: ["DEX"],
  },
  turbos: {
    jumbotron_image: "",
    logo: "",
    url: "https://app.turbos.finance/",
    title: "Turbos",
    description:
      "A hyper-efficient decentralized crypto marketplace built on Sui",
    tagline: "A hyper-efficient decentralized crypto marketplace built on Sui",
    tags: ["DEX"],
  },
  deepbook: {
    jumbotron_image: "",
    logo: "",
    url: "https://deepbook.tech/",
    title: "Deepbook",
    description: `DeepBook is a decentralized central limit order book (CLOB) built for the Sui ecosystem. DeepBook provides a one-stop shop for trading digital assets, with a technical design built for Sui’s architecture. DeepBook leverages Sui’s performance and delivers a low latency and high throughput execution engine to spread liquidity across the DeFi ecosystem.`,
    tagline: "",
    tags: [""],
  },
  kriya: {
    jumbotron_image: "/defi/kryia-app.png",
    logo: "",
    url: "https://kriya.finance",
    title: "Kriya",
    description: `1-stop DeFi protocol on Sui. Offering Swaps, Limit Orders, 1-click leverage lending strategies, Yield Optimiser Vaults and 20x perps`,
    tagline: "",
    tags: ["Yield", "Swaps", "Leverage", "Perpetuals"],
  },
  sudofinance: {
    jumbotron_image: "/defi/sudo-app.png",
    logo: "",
    url: "https://app.sudo.finance",
    title: "Sudo Finance",
    description: `Sudo is the first protocol that provides you access to a wide range of perpetual assets within the Sui ecosystem. As the first perpetuals aggregator platform, Sudo aims to provide the best perpetuals trading experience to tadres on Sui. `,
    tagline: "",
    tags: ["Perpetuals", "Aggretator"],
  },
  suilend: {
    jumbotron_image: "/defi/suilend-app.png",
    logo: "",
    url: "https://suilend.fi/",
    title: "Suilend",
    description:
      "Suilend is a lending protocol on Sui, built by the team behind Solend.",
    tagline:
      "Suilend is a lending protocol on Sui, built by the team behind Solend.",
    tags: ["Lending"],
  },
  scallop: {
    jumbotron_image: "/defi/scallop-app.jpg",
    logo: "",
    url: "https://app.scallop.io/",
    title: "Scallop",
    description:
      "Scallop is the pioneering Next Generation Money Market for the Sui ecosystem which emphasizes institutional-grade quality, enhanced composability, and robust security.",
    tagline: "",
    tags: ["Lending"],
  },
  alphafi: {
    jumbotron_image: "",
    logo: "",
    url: "https://alphafi.xyz/",
    title: "Alphafi",
    description: `Premier Yield Optimizer on the SUI Blockchain. Earn Safe, Real Yields with AlphaFi.`,
    tagline:
      "Premier Yield Optimizer on the SUI Blockchain. Earn Safe, Real Yields with AlphaFi.",
    tags: ["Yield Aggregator"],
  },
  bluefin: {
    jumbotron_image: "",
    logo: "",
    url: "https://bluefin.io/",
    title: "Bluefin",
    description: `Bluefin is a decentralized orderbook-based exchange built for both professional and first-time traders. It focuses on security, transparency and redefining the user experience of using on-chain trading platforms - and is backed by Polychain, SIG, Brevan Howard, and other leading firms`,
    tagline: "A Financial Network With Parallelized Performance",
    tags: ["Derivatives"],
  },
};

export const GAMING_APP_LIST: Record<string, APP_INFO> = {
  doubleup: {
    jumbotron_image: "/gaming/Diamond_Only.png",
    logo: "/gaming/doubleup-text-logo_380_120.png",
    url: "https://www.doubleup.fun/game/coinflip",
    title: "doubleup",
    description: `Experience the ultimate in privacy and freedom with DoubleUp Sui decentralized casino. Enjoy classic casino games but without the fuss of KYC.`,
    tagline: "Decentralized Casino on Sui",
    tags: ["Casino", "Yield"],
  },
  panzerdogs: {
    jumbotron_image: "/gaming/panzerdogs-app.png",
    logo: "",
    url: "",
    title: "Panzerdogs",
    description: ``,
    tagline: "",
    tags: [""],
  },
  cosmocadia: {
    jumbotron_image: "/gaming/cosmocadia-app.png",
    logo: "",
    url: "",
    title: "Cosmocadia",
    description: ``,
    tagline: "",
    tags: [""],
  },
  e4c: {
    jumbotron_image: "",
    logo: "",
    url: "",
    title: "E4C",
    description: ``,
    tagline: "",
    tags: [""],
  },
  cryptocatchfishingstar: {
    jumbotron_image: "",
    logo: "",
    url: "",
    title: "Crypto Catch Fishing Star",
    description: ``,
    tagline: "",
    tags: [""],
  },
  "winx.io": {
    jumbotron_image: "/gaming/winx-app.png",
    logo: "",
    url: "https://winx.io/",
    title: "WinX.io",
    description: `A crypto casino from the future `,
    tagline: "A crypto casino from the future ",
    tags: ["Casino"],
  },
};

export const ETC_APP_LIST: Record<string, APP_INFO> = {
  fourpillars: {
    jumbotron_image: "",
    logo: "/gaming/doubleup-text-logo_380_120.png",
    url: "http://4pillars.io/",
    title: "Four Pillars",
    description: `Blockchain Research Firm`,
    tagline: "",
    tags: [""],
  },
};

export const SOCIAL_APP_LIST: Record<string, APP_INFO> = {
  rootlets: {
    jumbotron_image: "",
    logo: "",
    url: "",
    title: "Rootlets",
    description: ``,
    tagline: "",
    tags: [""],
  },
  mirai: {
    jumbotron_image: "",
    logo: "",
    url: "",
    title: "Mirai",
    description: ``,
    tagline: "",
    tags: [""],
  },
  citizens: {
    jumbotron_image: "",
    logo: "",
    url: "https://www.doubleup.fun/citizens",
    title: "Citizens",
    description: ``,
    tagline: "",
    tags: [""],
  },
  rinoco: {
    jumbotron_image: "",
    logo: "",
    url: "",
    title: "Rinoco",
    description: ``,
    tagline: "",
    tags: [""],
  },
};

export const MEMECOINS_APP_LIST: Record<string, APP_INFO> = {
  fud: {
    jumbotron_image: "",
    logo: "",
    url: "",
    title: "FUD",
    description: ``,
    tagline: "",
    tags: [""],
  },
  liq: {
    jumbotron_image: "",
    logo: "",
    url: "",
    title: "LIQ",
    description: ``,
    tagline: "",
    tags: [""],
  },
  seb: {
    jumbotron_image: "",
    logo: "",
    url: "",
    title: "SEB",
    description: ``,
    tagline: "",
    tags: [""],
  },
  blub: {
    jumbotron_image: "",
    logo: "",
    url: "",
    title: "BLUB",
    description: ``,
    tagline: "",
    tags: [""],
  },
  aaacat: {
    jumbotron_image: "",
    logo: "",
    url: "",
    title: "AAACat",
    description: ``,
    tagline: "",
    tags: [""],
  },
  pup: {
    jumbotron_image: "",
    logo: "",
    url: "",
    title: "PUP",
    description: ``,
    tagline: "",
    tags: [""],
  },
};

export const ALL_APP_LIST: Record<string, APP_INFO> = {
  ...DEFI_APP_LIST,
  ...GAMING_APP_LIST,
  ...ETC_APP_LIST,
  ...SOCIAL_APP_LIST,
  ...MEMECOINS_APP_LIST,
  eample: {
    jumbotron_image: "",
    logo: "",
    url: "",
    title: "",
    description: ``,
    tagline: "",
    tags: [""],
  },
};

export const EXAMPLE_APP_LIST: Record<string, APP_INFO> = {
  eample: {
    jumbotron_image: "",
    logo: "",
    url: "",
    title: "",
    description: ``,
    tagline: "",
    tags: [""],
  },
};
