export const DEFI_APP_LIST: Record<string, APP_INFO> = {
  aftermath: {
    jumbotron_image: "/defi/aftermath-app.png",
    logo: "",
    url: "https://aftermath.finance/",
    title: "Aftermath",
    description: "The ease of a centralized exchange with none of the risk.",
    tagline: "Cex On-Chain",
    tags: ["Aggretator", "DEX", "Liquid Staking"],
    twitter: "https://x.com/AftermathFi",
  },
  navi: {
    jumbotron_image: "/defi/navi-app.png",
    logo: "",
    url: "https://naviprotocol.io/",
    title: "Navi",
    description: `NAVI offers over collateralized lending/borrowing for SUI, USDC, USDT, wETH and wBTC and supports features like isolated pool, flash loan and soon to come crosschain lending/borrowing.`,
    tagline: "Lending platform on Sui",
    tags: ["Lending"],
    twitter: "https://x.com/navi_protocol",
  },
  flowx: {
    jumbotron_image: "/defi/flowx-app.png",
    logo: "",
    url: "https://flowx.finance/",
    title: "FlowX",
    description: `FlowX Finance is the ecosystem-focused decentralized exchange built on the Sui Blockchain`,
    tagline:
      "FlowX Finance is the ecosystem-focused decentralized exchange built on the Sui Blockchain",
    tags: ["DEX"],
    twitter: "https://x.com/FlowX_finance",
  },
  bucket: {
    jumbotron_image: "/defi/bucket-app.png",
    logo: "",
    url: "https://www.bucketprotocol.io/",
    title: "Bucket",
    description: "some coin thingy",
    tagline: "Bucket Protocol",
    tags: ["CDP"],
    twitter: "https://x.com/bucket_protocol",
  },
  suilend: {
    jumbotron_image: "/defi/suilend-app.jpeg",
    logo: "",
    url: "https://suilend.fi/",
    title: "Suilend",
    description:
      "Suilend is a lending protocol on Sui, built by the team behind Solend.",
    tagline:
      "Suilend is a lending protocol on Sui, built by the team behind Solend.",
    tags: ["Lending"],
    twitter: "https://x.com/suilendprotocol",
  },
  typusfinance: {
    jumbotron_image: "/defi/typus-app.png",
    logo: "",
    url: "https://typus.finance/",
    title: "Typus Finance",
    description: `Real yield infrastructure on Sui`,
    tagline: "Real yield infrastructure on Sui",
    tags: ["Yield"],
    twitter: "https://x.com/TypusFinance",
  },
  molefi: {
    jumbotron_image: "/defi/molefi-app.png",
    logo: "",
    url: "https://mole.fi/",
    title: "Molefi",
    description: `Mole is a DeFi protocol provided leveraged yield farming, hedge fund and savings.`,
    tagline:
      "Mole is a DeFi protocol provided leveraged yield farming, hedge fund and savings.",
    tags: ["Yield"],
    twitter: "https://x.com/moledefi",
  },
  cetus: {
    jumbotron_image: "/defi/cetus-app.webp",
    logo: "",
    url: "https://app.cetus.zone/",
    title: "Cetus",
    description:
      "Cetus is a pioneer DEX and concentrated liquidity protocol focusing on Move-based ecosystems like Aptos and Sui. It works as a crucial part of the ecosystem infrastructure to satisfy the comprehensive needs of traders, LPs, upper applications and an increasing DeFi population.",
    tagline: "",
    tags: ["DEX"],
    twitter: "https://x.com/CetusProtocol",
  },
  turbos: {
    jumbotron_image: "/defi/turbos-app.png",
    logo: "",
    url: "https://app.turbos.finance/",
    title: "Turbos",
    description:
      "A hyper-efficient decentralized crypto marketplace built on Sui",
    tagline: "A hyper-efficient decentralized crypto marketplace built on Sui",
    tags: ["DEX"],
    twitter: "https://x.com/Turbos_finance",
  },
  kriya: {
    jumbotron_image: "/defi/kryia-app.png",
    logo: "",
    url: "https://kriya.finance",
    title: "Kriya",
    description: `1-stop DeFi protocol on Sui. Offering Swaps, Limit Orders, 1-click leverage lending strategies, Yield Optimiser Vaults and 20x perps`,
    tagline: "",
    tags: ["Yield", "Swaps", "Leverage", "Perpetuals"],
    twitter: "https://x.com/KriyaDEX",
  },
  sudofinance: {
    jumbotron_image: "/defi/sudo-app.png",
    logo: "",
    url: "https://app.sudo.finance",
    title: "Sudo Finance",
    description: `Sudo is the first protocol that provides you access to a wide range of perpetual assets within the Sui ecosystem. As the first perpetuals aggregator platform, Sudo aims to provide the best perpetuals trading experience to tadres on Sui. `,
    tagline: "",
    tags: ["Perpetuals", "Aggretator"],
    twitter: "https://x.com/sudofinance",
  },
  scallop: {
    jumbotron_image: "/defi/scallop-app.jpg",
    logo: "",
    url: "https://app.scallop.io/",
    title: "Scallop",
    description:
      "Scallop is the pioneering Next Generation Money Market for the Sui ecosystem which emphasizes institutional-grade quality, enhanced composability, and robust security.",
    tagline: "",
    tags: ["Lending"],
    twitter: "https://x.com/Scallop_io",
  },
  alphafi: {
    jumbotron_image: "/defi/alphafi-app.png",
    logo: "",
    url: "https://alphafi.xyz/",
    title: "Alphafi",
    description: `Premier Yield Optimizer on the SUI Blockchain. Earn Safe, Real Yields with AlphaFi.`,
    tagline:
      "Premier Yield Optimizer on the SUI Blockchain. Earn Safe, Real Yields with AlphaFi.",
    tags: ["Yield Aggregator"],
    twitter: "https://x.com/AlphaFiSUI",
  },
  bluefin: {
    jumbotron_image: "/defi/bluefin-app.png",
    logo: "",
    url: "https://bluefin.io/",
    title: "Bluefin",
    description: `Bluefin is a decentralized orderbook-based exchange built for both professional and first-time traders. It focuses on security, transparency and redefining the user experience of using on-chain trading platforms - and is backed by Polychain, SIG, Brevan Howard, and other leading firms`,
    tagline: "A Financial Network With Parallelized Performance",
    tags: ["Trading"],
    twitter: "https://x.com/bluefinapp",
  },
};

export const GAMING_APP_LIST: Record<string, APP_INFO> = {
  doubleup: {
    jumbotron_image: "/gaming/doubleup-jumbotron.png",
    logo: "/gaming/doubleup-text-logo_380_120.png",
    url: "https://www.doubleup.fun/game/coinflip",
    title: "DoubleUp",
    description: `Enjoy classic games but without the fuss of KYC.`,
    tagline: "Decentralized gaming platform on Sui",
    tags: ["Gaming"],
    twitter: "https://x.com/doubleup_app",
  },
  panzerdogs: {
    jumbotron_image: "/gaming/panzerdogs-app.png",
    logo: "",
    url: "https://www.panzerdogs.io/",
    title: "Panzerdogs",
    description: "An exciting top down shooter featuring cute dogs.",
    tagline: "pew pew pew",
    tags: ["Gaming"],
    twitter: "https://x.com/panzerdogs",
  },
  cosmocadia: {
    jumbotron_image: "/gaming/cosmocadia-app.png",
    logo: "",
    url: "https://www.cosmocadia.io/",
    title: "Cosmocadia",
    description:
      "Embark on an epic journey armed with your trusty axe, as you shape and cultivate an entire world. Delve into exploration, harvest resources, construct, cultivate, and master the art of crafting to forge your utopia. Prove your mayoral prowess in this captivating and addictive casual simulator.",
    tagline: "",
    tags: ["Gaming"],
    twitter: "https://x.com/Cosmocadia",
  },
  cryptocatchfishingstar: {
    jumbotron_image: "/gaming/fishing-app.png",
    logo: "",
    url: "https://ccfishingstar.blrd.inc/",
    title: "Crypto Catch Fishing Star",
    description: "Hypercasual fishing game on Sui",
    tagline: "fish fish fish",
    tags: ["Gaming"],
    twitter: "https://x.com/CC_FishingStar",
  },
  "winx.io": {
    jumbotron_image: "/gaming/winx-app.png",
    logo: "",
    url: "https://winx.io/",
    title: "WinX.io",
    description: `A crypto casino from the future `,
    tagline: "A crypto casino from the future ",
    tags: ["Casino"],
    twitter: "https://x.com/WinX_io",
  },
};

export const ETC_APP_LIST: Record<string, APP_INFO> = {
  fourpillars: {
    jumbotron_image: "/etc/four-pillars-jumbotron.jpeg",
    logo: "/etc/four-pillars-logo.png",
    url: "http://4pillars.io/",
    title: "Four Pillars",
    description: `Blockchain Research Firm`,
    tagline: "Abstract Away, Build the Real Blocks",
    tags: [""],
    twitter: "https://x.com/fourpillarsfp",
  },
};

export const SOCIAL_APP_LIST: Record<string, APP_INFO> = {
  rootlets: {
    jumbotron_image: "/social/rootlets-jumbotron.jpeg",
    logo: "/social/rootlets-logo.jpg",
    url: "https://rootlets.io/",
    title: "Rootlets",
    description: `Cute creatures have come from the Suiverse to colonize Earth! Get ready, let’s r🐽t!`,
    tagline:
      "Cute creatures have come from the Suiverse to colonize Earth! Get ready, let’s r🐽t!",
    tags: [""],
    twitter: "https://x.com/rootlets_nft",
  },
  mirai: {
    jumbotron_image: "",
    logo: "",
    url: "",
    title: "Mirai",
    description: ``,
    tagline: "",
    tags: [""],
    twitter: "",
  },
  citizens: {
    jumbotron_image: "/gaming/doubleup-jumbotron.png",
    logo: "/gaming/doubleup-text-logo_380_120.png",
    url: "https://www.doubleup.fun/citizens",
    title: "Citizens",
    description: ``,
    tagline: "",
    tags: [""],
    twitter: "https://x.com/doubleup_app",
  },
  rinoco: {
    jumbotron_image: "/social/rinoco-jumbotron.jpeg",
    logo: "/social/rinoco-logo.jpg",
    url: "https://www.rinoco.world/",
    title: "Rinoco",
    description: `Where the cutest creatures are all gathered! 🐾`,
    tagline: "Where the cutest creatures are all gathered! 🐾",
    tags: [""],
    twitter: "https://x.com/RinocoOfficial",
  },
};

export const MEMECOINS_APP_LIST: Record<string, APP_INFO> = {
  fud: {
    jumbotron_image: "/memecoins/fud-jumbotron.jpeg",
    logo: "/memecoins/fud-logo.jpg",
    url: "https://fudthepug.com/",
    title: "FUD",
    description: `"$FUD is the OG meme on Sui. Our mission is to spread fun, stupidity and Sui."`,
    tagline: "FUD is Fuel",
    tags: [""],
    twitter: "https://x.com/fudthepug",
  },
  liq: {
    jumbotron_image: "/memecoins/liquor-jumbotron.jpeg",
    logo: "/memecoins/liquor-logo.jpg",
    url: "https://www.beliquoronsui.com/",
    title: "LIQ",
    description: `Be rich, be liquor`,
    tagline: "Be rich, be liquor",
    tags: [""],
    twitter: "https://x.com/Beliquoronsui",
  },
  seb: {
    jumbotron_image: "",
    logo: "",
    url: "",
    title: "SEB",
    description: ``,
    tagline: "",
    tags: [""],
    twitter: "",
  },
  blub: {
    jumbotron_image: "/memecoins/blub-jumbotron.jpeg",
    logo: "/memecoins/blub-logo.jpg",
    url: "https://www.blubsui.com/",
    title: "BLUB",
    description: `$BLUB is the funniest and most degenerate fish in the Sui Ocean, staying true to its origins and bringing the chaotic energy of the 'Boy's Club'.`,
    tagline:
      "A Dirty Fish in the Waters of the Sui Ocean. The #1 Meme on $SUI.",
    tags: [""],
    twitter: "https://x.com/blubsui",
  },
  aaacat: {
    jumbotron_image: "/memecoins/aaa-jumbotron.jpeg",
    logo: "/memecoins/aaa-logo.jpg",
    url: "https://aaacatsui.com/",
    title: "AAACat",
    description: `aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa`,
    tagline: "AAAAAAAAAAAAA",
    tags: [""],
    twitter: "https://x.com/aaaCatSui",
  },
  pup: {
    jumbotron_image: "/memecoins/pup-logo.jpg",
    logo: "/memecoins/pup-logo.jpg",
    url: "",
    title: "PUP",
    description: `The first(and best) Casino Dog on Sui`,
    tagline: "The first(and best) Casino Dog on Sui",
    tags: [""],
    twitter: "https://x.com/PumPupSui",
  },
};

export const ALL_APP_LIST: Record<string, APP_INFO> = {
  ...DEFI_APP_LIST,
  ...GAMING_APP_LIST,
  ...ETC_APP_LIST,
  ...SOCIAL_APP_LIST,
  ...MEMECOINS_APP_LIST,
  eample: {
    jumbotron_image: "",
    logo: "",
    url: "",
    title: "",
    description: ``,
    tagline: "",
    tags: [""],
    twitter: "",
  },
};

export const EXAMPLE_APP_LIST: Record<string, APP_INFO> = {
  eample: {
    jumbotron_image: "",
    logo: "",
    url: "",
    title: "",
    description: ``,
    tagline: "",
    tags: [""],
    twitter: "",
  },
};
